### ISSUE TITLE
Immediate to-do

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/obsidian-sortable#1]
- [x] arrows should be displayed only on "sortable" tables => "this.asc"
- [x] want the event to happen only when clicking on headers
- [x] change css for sorting direction

### References
- https://javascript.plainenglish.io/easy-table-sorting-with-javascript-370d8d97cad8
- https://stackoverflow.com/questions/14267781/sorting-html-table-with-javascript
